services:
  id-front:
    build:
      context: ./components/id-front
    restart: on-failure
    ports:
      - "${SVC_ID_PORT}:8080"
    volumes:
      - ./config/id/config.json:/usr/share/nginx/html/config.json:ro
    depends_on:
      - id-api

  id-api:
    build:
      context: ./components/id-api
      additional_contexts:
        back-core: ./packages/back-core
    restart: on-failure
    ports:
      - "${SVC_ID_API_PORT}:8100"
    volumes:
      - ./config/id:/var/www/config:ro
    depends_on:
      - id-migrations
      - rabbitmq
      - redis

  id-migrations:
    build:
      context: ./components/id-api
      additional_contexts:
        back-core: ./packages/back-core
    command: ["npm", "run", "migration-up"]
    restart: on-failure
    volumes:
      - ./config/id:/var/www/config:ro
    depends_on:
      - postgres

  admin-api:
    build:
      context: ./components/admin-api
      additional_contexts:
        back-core: ./packages/back-core
    restart: on-failure
    ports:
      - "${SVC_ADMIN_API_PORT}:8102"
    volumes:
      - ./config/admin-api:/var/www/config:ro
    depends_on:
      - postgres
      - rabbitmq
      - redis

  admin-front:
    build:
      context: ./components/admin-front
      args:
        NODE_MAX_OLD_SPACE_SIZE: 1536
        GENERATE_SOURCEMAP: ${GENERATE_SOURCEMAP:-false}
        DISABLE_ESLINT_PLUGIN: ${DISABLE_ESLINT_PLUGIN:-true}
        INLINE_RUNTIME_CHUNK: ${INLINE_RUNTIME_CHUNK:-false}
      additional_contexts:
        core: ./packages/front-core
    restart: on-failure
    ports:
      - "${SVC_ADMIN_FRONT_PORT}:8080"
    volumes:
      - ./config/admin-front/config.json:/usr/share/nginx/html/config.json:ro
    depends_on:
      - admin-api

  cabinet-api:
    build:
      context: ./components/cabinet-api
      additional_contexts:
        back-core: ./packages/back-core
    restart: on-failure
    ports:
      - "${SVC_CABINET_API_PORT}:8101"
    volumes:
      - ./config/cabinet-api:/var/www/config:ro
    depends_on:
      - postgres
      - redis

  cabinet-front:
    build:
      context: ./components/cabinet-front
      args:
        NODE_MAX_OLD_SPACE_SIZE: 1536
        GENERATE_SOURCEMAP: ${GENERATE_SOURCEMAP:-false}
        DISABLE_ESLINT_PLUGIN: ${DISABLE_ESLINT_PLUGIN:-true}
        INLINE_RUNTIME_CHUNK: ${INLINE_RUNTIME_CHUNK:-false}
      additional_contexts:
        core: ./packages/front-core
    restart: on-failure
    ports:
      - "${SVC_CABINET_FRONT_PORT}:8080"
    volumes:
      - ./config/cabinet-front/config.json:/usr/share/nginx/html/config.json:ro
    depends_on:
      - cabinet-api

  manager-migrations:
    build:
      context: ./components/manager
    command: ["npm", "run", "migration-up"]
    restart: on-failure
    volumes:
      - ./config/manager:/var/www/config:ro
    depends_on:
      - postgres

  manager:
    build:
      context: ./components/manager
    restart: on-failure
    volumes:
      - ./config/manager:/var/www/config:ro
    depends_on:
      - manager-migrations
      - rabbitmq
      - redis

  register:
    build:
      context: ./components/register
    restart: on-failure
    ports:
      - "${SVC_REGISTER_PORT}:8103"
    volumes:
      - ./config/register:/var/www/config:ro
    depends_on:
      - register-migrations

  register-migrations:
    build:
      context: ./components/register
    command: ["npm", "run", "migration-up"]
    restart: on-failure
    volumes:
      - ./config/register:/var/www/config:ro
    depends_on:
      - postgres
      - rabbitmq
      - redis

  event:
    build:
      context: ./components/event
      additional_contexts:
        back-core: ./packages/back-core
    restart: on-failure
    volumes:
      - ./config/event:/var/www/config:ro
    depends_on:
      - postgres
      - rabbitmq
      - redis

  gateway:
    build:
      context: ./components/gateway
    restart: on-failure
    volumes:
      - ./config/gateway:/var/www/config:ro
    depends_on:
      - postgres
      - rabbitmq
      - redis

  sign-tool:
    build:
      context: ./components/sign-tool
    restart: on-failure
    ports:
      - "${SVC_SIGN_TOOL_PORT}:3004"
    volumes:
      - ./config/sign-tool:/var/www/config:ro

  task:
    build:
      context: ./components/task
    restart: on-failure
    volumes:
      - ./config/task:/var/www/config:ro
    depends_on:
      - postgres
      - rabbitmq
      - redis

  notification:
    build:
      context: ./components/notification
    restart: on-failure
    volumes:
      - ./config/notification:/var/www/config:ro
    depends_on:
      - notification-migrations

  notification-migrations:
    build:
      context: ./components/notification
    command: ["npm", "run", "migration-up"]
    restart: on-failure
    volumes:
      - ./config/notification:/var/www/config:ro
    depends_on:
      - postgres

  external-reader:
    build:
      context: ./components/external-reader
    restart: on-failure
    ports:
      - "${SVC_EXTERNAL_READER_PORT}:8104"
    volumes:
      - ./config/external-reader:/var/www/config:ro

  pdf-generator:
    build:
      context: ./components/pdf-generator
    restart: on-failure
    ports:
      - "${SVC_PDF_GENERATOR_PORT}:7007"
    volumes:
      - ./config/pdf-generator:/var/www/config:ro

  filestorage:
    build:
      context: ./components/filestorage
      additional_contexts:
        back-core: ./packages/back-core
    restart: on-failure
    ports:
      - "${SVC_FILESTORAGE_PORT}:8105"
    volumes:
      - ./config/filestorage:/var/www/config:ro
    depends_on:
      - filestorage-migrations

  filestorage-migrations:
    build:
      context: ./components/filestorage
      additional_contexts:
        back-core: ./packages/back-core
    command: ["npm", "run", "migration-up"]
    restart: on-failure
    volumes:
      - ./config/filestorage:/var/www/config:ro
    depends_on:
      - postgres

  persist-link-migrations:
    build:
      context: ./components/persist-link
    command: ["npm", "run", "migration-up"]
    restart: on-failure
    volumes:
      - ./config/persist-link:/var/www/config:ro
    depends_on:
      - postgres

  persist-link:
    build:
      context: ./components/persist-link
    restart: on-failure
    ports:
      - "${SVC_PERSIST_LINK_PORT}:3346"
    volumes:
      - ./config/persist-link:/var/www/config:ro
    depends_on:
      - persist-link-migrations
      - postgres

  postgres:
    image: postgres:17
    ports:
      - "${POSTGRES_PUBLISHED_PORT:-5432}:5432"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_NAME: ${POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/db/:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_MANAGEMENT_PUBLISHED_PORT:-15672}:15672"
      - "${RABBITMQ_AMQP_PUBLISHED_PORT:-5672}:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PUBLISHED_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
