apiVersion: v2
name: liquio
description: A Helm chart for Liquio platform
type: application
version: 0.3.47
appVersion: "0.1.0"
icon: https://raw.githubusercontent.com/liquio/liquio/refs/heads/main/helm-chart/icon.svg
