{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.fullname" . }}-redis-master
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "liquio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
