{{- if not .Values.secrets.existingSecretConfig }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.secretConfig.name" (dict "ctx" . "service" "event") }}
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
    app.kubernetes.io/component: event
type: Opaque
stringData:
  db.json: |
    { "password": "{{ include "liquio.postgresql.passwordValue" . }}" }
  message_queue.json: |
    { "amqpConnection": "amqp://{{ .Values.config.rabbitmq.username }}:{{ include "liquio.rabbitmq.passwordValue" . }}@{{ include "liquio.rabbitmq.host" . }}:{{ .Values.config.rabbitmq.port }}/" }
  filestorage.json: |
    { "token": "{{ include "liquio.filestorage.authTokenValue" . }}" }
  requester.json: |
    { "registers": { "token": "Basic {{ include "liquio.register.authTokenValue" . }}" } }
  notifier.json: |
    { "email": { "user": "{{ include "liquio.notification.userValue" . }}", "hashedPassword": "{{ include "liquio.notification.passwordValue" . }}" }, "sms": { "user": "{{ include "liquio.notification.userValue" . }}", "hashedPassword": "{{ include "liquio.notification.passwordValue" . }}" } }
  system_notifier.json: |
    { "email": { "user": "{{ include "liquio.notification.userValue" . }}", "hashedPassword": "{{ include "liquio.notification.passwordValue" . }}" } }
{{- end }}
