{{- if not .Values.secrets.existingSecretConfig }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.secretConfig.name" (dict "ctx" . "service" "external-reader") }}
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
    app.kubernetes.io/component: external-reader
type: Opaque
stringData:
  auth.json: |
    { "basicAuthTokens": ["external-reader:{{ include "liquio.externalReader.authTokenValue" . | b64dec | splitList ":" | rest | join ":" }}"] }
{{- end }}
