{{- if not .Values.secrets.existingSecretConfig }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.secretConfig.name" (dict "ctx" . "service" "filestorage") }}
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
    app.kubernetes.io/component: filestorage
type: Opaque
stringData:
  db.json: |
    { "password": "{{ include "liquio.postgresql.passwordValue" . }}" }
  auth.json: |
    { "token": "{{ include "liquio.filestorage.authTokenValue" . }}" }
{{- end }}
