{{- if .Values.services.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.fullname" . }}-gateway
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.services.gateway.type }}
  ports:
    - port: {{ .Values.services.gateway.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "liquio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
{{- end }}
