{{- if not .Values.secrets.existingSecretConfig }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.secretConfig.name" (dict "ctx" . "service" "notification") }}
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
    app.kubernetes.io/component: notification
type: Opaque
stringData:
  config.json: |
    {
      "production": {
        "password": "{{ include "liquio.postgresql.passwordValue" . }}",
        "db": { "password": "{{ include "liquio.postgresql.passwordValue" . }}" }
      }
    }
{{- end }}
