{{- if and .Values.services.register.enabled .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.fullname" . }}-register-migrations
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
    app.kubernetes.io/component: register-migrations
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "liquio.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: register-migrations
    spec:
      restartPolicy: Never
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "liquio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "liquio.initContainer.waitForPostgres" . | nindent 8 }}
        {{- include "liquio.initContainer.waitForRabbitmq" . | nindent 8 }}
        {{- include "liquio.initContainer.waitForRedis" . | nindent 8 }}
      containers:
        - name: register-migrations
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "liquio.image" (dict "component" "register" "Values" .Values "Chart" .Chart) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["npm", "run", "migration-up"]
          env:
            - name: NODE_ENV
              value: "production"
            - name: CONFIG_PATH
              value: "/var/www/config"
          volumeMounts:
            - name: config
              mountPath: /var/www/config
              readOnly: true
            - name: tmp
              mountPath: /tmp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "liquio.fullname" . }}-register-config
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
