apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.fullname" . }}-sign-tool-config
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
{{ $serverBase := dict
  "port" (default 8080 .Values.services.signTool.containerPort)
  "host" "0.0.0.0"
  "isSwaggerEnabled" false
  "acceptedBodySize" "10mb"
}}
data:
  # Server configuration
  server.json: |
{{ include "liquio.renderJsonConfig" (dict "ctx" . "service" "signTool" "config" "server" "base" $serverBase) | nindent 4 }}
