apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.fullname" . }}-sign-tool-config
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
data:
  # Server configuration
  server.json: |
    {
      "port": {{ .Values.services.signTool.targetPort }},
      "host": "0.0.0.0",
      "isSwaggerEnabled": false,
      "acceptedBodySize": "10mb"
    }
