{{- if not .Values.secrets.existingSecretConfig }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.secretConfig.name" (dict "ctx" . "service" "task") }}
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
    app.kubernetes.io/component: task
type: Opaque
stringData:
  db.json: |
    { "password": "{{ include "liquio.postgresql.passwordValue" . }}" }
  message_queue.json: |
    { "amqpConnection": "amqp://{{ .Values.config.rabbitmq.username }}:{{ include "liquio.rabbitmq.passwordValue" . }}@{{ include "liquio.rabbitmq.host" . }}:{{ .Values.config.rabbitmq.port }}/" }
  auth.json: |
    { "LiquioId": { "clientSecret": "{{ include "liquio.oauth.secretKeyValue" . }}", "basicAuthToken": "{{ include "liquio.oauth.secretKeyValue" . }}" }, "jwtSecret": "{{ include "liquio.jwt.secretValue" . }}" }
  register.json: |
    { "token": "Basic {{ include "liquio.register.authTokenValue" . }}" }
  external_reader.json: |
    { "basicAuthToken": "{{ include "liquio.externalReader.authTokenValue" . }}" }
  filestorage.json: |
    { "token": "{{ include "liquio.filestorage.authTokenValue" . }}" }
  storage.json: |
    { "FileStorage": { "token": "{{ include "liquio.filestorage.authTokenValue" . }}" } }
  download_token.json: |
    { "jwtSecret": "{{ include "liquio.jwt.secretValue" . }}" }
  notifier.json: |
    { "user": "{{ include "liquio.notification.userValue" . }}", "hashedPassword": "{{ include "liquio.notification.passwordValue" . }}" }
  system_notifier.json: |
    { "email": { "user": "{{ include "liquio.notification.userValue" . }}", "hashedPassword": "{{ include "liquio.notification.passwordValue" . }}" } }
{{- end }}
