apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.fullname" . }}-admin-front-config
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
{{ $configBase := dict
  "application" (dict
    "name" "Admin Panel"
    "environment" "development"
    "type" "adminpanel"
  )
  "customers" (list
    (dict "id" 1 "name" "bpmn")
  )
  "registry" (dict
    "useReindex" true
    "useAfterhandlersReindex" true
  )
  "reports" (dict
    "enabled" true
  )
  "useUIFilters" true
  "customInterfaces" true
  "plugins" (list)
  "backendUrl" (printf "%s://%s" (include "liquio.scheme" .) (include "liquio.publicHost" (dict "ctx" . "service" "admin-api")))
  "authLink" (printf "%s://%s/redirect/auth" (include "liquio.scheme" .) (include "liquio.publicHost" (dict "ctx" . "service" "admin-api")))
  "adminPanelUrl" (printf "%s://%s" (include "liquio.scheme" .) (include "liquio.publicHost" (dict "ctx" . "service" "admin")))
  "cabinetUrl" (printf "%s://%s" (include "liquio.scheme" .) (include "liquio.publicHost" (dict "ctx" . "service" "cabinet")))
  "sentryDns1" "https://sentry"
  "sessionLifeTime" 480
  "enabledMock" false
  "clientId" "liquio-portal"
  "idAuthLink" (printf "%s://%s/authorise" (include "liquio.scheme" .) (include "liquio.publicHost" (dict "ctx" . "service" "id")))
  "enabledDeleteUser" false
  "enabledMocksPage" false
  "defaultLanguage" "en"
  "hideQr" true
}}
data:
  config.json: |
{{ include "liquio.renderJsonConfig" (dict "ctx" . "service" "adminFront" "config" "config" "base" $configBase) | nindent 4 }}
