const UNIT_ADMIN_UNIT = 1000000;
const SECURITY_ADMIN_UNIT = 1000001;
const SYSTEM_ADMIN_UNIT = 1000002;
const SUPPORT_ADMIN_UNIT = 1000003;
const READONLY_SECURITY_ADMIN_UNIT = 1000000041;
const READONLY_SYSTEM_ADMIN_UNIT = 1000000042;
const READONLY_SUPPORT_ADMIN_UNIT = 1000000043;
const WORKFLOW_SYSTEM_ADMIN_UNIT = 100002;
const WORKFLOW_SUPPORT_ADMIN_UNIT = 100003;
const ELASTIC_ADMIN = 1000012;
const SNIPPETS_ADMIN_UNIT = 1000015;
const TAG_ADMIN_UNIT = 1000017;
const ONLY_MOCS_DEBUG_TOOLS_UNIT = 1000000190;

const ADMIN_UNITS = [
  UNIT_ADMIN_UNIT,
  SECURITY_ADMIN_UNIT,
  SYSTEM_ADMIN_UNIT,
  SUPPORT_ADMIN_UNIT,
  READONLY_SECURITY_ADMIN_UNIT,
  READONLY_SYSTEM_ADMIN_UNIT,
  READONLY_SUPPORT_ADMIN_UNIT,
  WORKFLOW_SYSTEM_ADMIN_UNIT,
  WORKFLOW_SUPPORT_ADMIN_UNIT,
  ELASTIC_ADMIN,
  SNIPPETS_ADMIN_UNIT,
  ONLY_MOCS_DEBUG_TOOLS_UNIT,
];

module.exports = {
  UNIT_ADMIN_UNIT,
  SECURITY_ADMIN_UNIT,
  SYSTEM_ADMIN_UNIT,
  SUPPORT_ADMIN_UNIT,
  READONLY_SECURITY_ADMIN_UNIT,
  READONLY_SYSTEM_ADMIN_UNIT,
  READONLY_SUPPORT_ADMIN_UNIT,
  WORKFLOW_SYSTEM_ADMIN_UNIT,
  WORKFLOW_SUPPORT_ADMIN_UNIT,
  ELASTIC_ADMIN,
  SNIPPETS_ADMIN_UNIT,
  ONLY_MOCS_DEBUG_TOOLS_UNIT,
  ADMIN_UNITS,
  TAG_ADMIN_UNIT,
};
