
const Sequelize = require('sequelize');
const Model = require('./model');
const DocumentAttachmentEntity = require('../entities/document_attachment');

/**
 * Document attachment model.
 */
class DocumentAttachmentModel extends Model {
  /**
   * Document attachment model constructor.
   */
  constructor() {
    if (!DocumentAttachmentModel.singleton) {
      super();

      this.model = this.db.define(
        'documentAttachment',
        {
          id: { primaryKey: true, type: Sequelize.UUID, defaultValue: Sequelize.UUIDV1 },
          document_id: {
            type: Sequelize.UUID,
            references: { model: 'documents', key: 'id' }
          },
          link: Sequelize.STRING,
          name: Sequelize.STRING,
          type: Sequelize.STRING,
          size: Sequelize.INTEGER,
          labels: {
            type: Sequelize.ARRAY(Sequelize.STRING),
            allowNull: false,
            defaultValue: []
          },
          is_generated: {
            type: Sequelize.BOOLEAN,
            allowNull: false,
            defaultValue: false
          },
          is_system: {
            type: Sequelize.BOOLEAN,
            allowNull: false,
            defaultValue: false
          },
          meta: {
            type: Sequelize.JSONB,
            allowNull: false,
            defaultValue: {}
          }
        },
        {
          tableName: 'document_attachments',
          underscored: true,
          createdAt: 'created_at',
          updatedAt: 'updated_at'
        }
      );

      DocumentAttachmentModel.singleton = this;
    }

    return DocumentAttachmentModel.singleton;
  }

  /**
   * Find by ID.
   * @param {string} id UUID.
   * @returns {Promise<DocumentAttachmentEntity>}
   */
  async findById(id) {
    const attachment = await this.model.findByPk(id);

    if (!attachment) { return; }

    return this.prepareEntity(attachment);
  }

  /**
   * Get by document ID.
   * @param {string} documentId Document ID.
   * @returns {Promise<DocumentAttachmentEntity[]>} Promise of document attachments list.
   */
  async getByDocumentId(documentId) {
    // Get attachments RAW records from DB.
    const attachmentsRaw = await this.model.findAll({ where: { document_id: documentId } });

    // Define and return attachments entities.
    const attachments = attachmentsRaw.map(this.prepareEntity).sort((a, b) => +(a.id > b.id));
    return attachments;
  }

  /**
   * Get by document id and meta.
   * @param {string} documentId Document ID.
   * @param {Object} meta Attachment meta property.
   * @returns {Promise<DocumentAttachmentEntity[]>} Promise of document attachments list.
   */
  async getByDocumentIdAndMeta(documentId, meta) {
    // Get attachments RAW records from DB.
    const attachmentsRaw = await this.model.findAll({ where: { document_id: documentId, meta: meta } });

    // Return attachments entities.
    return attachmentsRaw.map(this.prepareEntity).sort((a, b) => +(a.id > b.id));
  }

  /**
   * Get by document IDs.
   * @param {string} documentIds Document ID.
   * @returns {Promise<DocumentAttachmentEntity[]>} Promise of document attachments list.
   */
  async getByDocumentIds(documentIds) {
    // Get attachments RAW records from DB.
    const attachmentsRaw = await this.model.findAll({ where: { document_id: documentIds } });

    // Define and return attachments entities.
    const attachments = attachmentsRaw.map(this.prepareEntity).sort((a, b) => +(a.id > b.id));
    return attachments;
  }

  /**
   * Create attachment.
   * @param {object} data Data object.
   * @param {string} data.documentId Document ID.
   * @param {string} data.link Link.
   * @param {string} data.name Name.
   * @param {boolean} [data.isGenerated] Is generated indicator.
   * @param {boolean} [data.isSystem] Is system.
   * @param {string} data.type Type.
   * @param {string[]} data.labels Labels.
   * @param {object} data.meta Meta.
   */
  async create({ documentId, link, name, type, size = 0, labels = [], isGenerated = false, isSystem = false, meta = {} }) {
    const attachment = this.prepareForModel({ documentId, link, name, type, size, labels, isGenerated, isSystem, meta });
    const rawDbResponse = await this.model.create(attachment);

    return this.prepareEntity(rawDbResponse);
  }

  /**
   * Delete attachment.
   * @param {string} id UUID.
   */
  async delete(id) {
    const result = await this.model.destroy({ where: { id: id } });

    return result;
  }

  /**
   * Delete by document ID.
   * @param {string} documentId Document ID.
   * @returns {Promise<number>}
   */
  async deleteByDocumentId(documentId) {
    await this.model.destroy({ where: { document_id: documentId } });
  }

  /**
   * Delete generated by document ID.
   * @param {string} documentId Document ID.
   * @returns {Promise<number>}
   */
  async deleteGeneratedByDocumentId(documentId) {
    await this.model.destroy({ where: { document_id: documentId, is_generated: true } });
  }

  /**
   * Prepare entity.
   * @param {object} item Item.
   * @returns {DocumentEntity}
   */
  prepareEntity(item) {
    return new DocumentAttachmentEntity({
      id: item.id,
      documentId: item.document_id,
      link: item.link,
      name: item.name,
      type: item.type,
      size: item.size,
      labels: item.labels,
      isGenerated: item.is_generated,
      isSystem: item.is_system,
      meta: item.meta,
      createdAt: item.created_at
    });
  }

  /**
   * Prepare for model.
   * @param {DocumentAttachmentEntity} item Item.
   * @returns {object}
   */
  prepareForModel(item) {
    return {
      document_id: item.documentId,
      link: item.link,
      name: item.name,
      type: item.type,
      size: item.size,
      labels: item.labels,
      is_generated: item.isGenerated,
      is_system: item.isSystem,
      meta: item.meta,
    };
  }
}

module.exports = DocumentAttachmentModel;
