apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.fullname" . }}-cabinet-front-config
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
{{ $configBase := dict
  "application" (dict
    "name" "liquio"
    "environment" "dev"
    "type" "manager"
    "version" "0.1.0"
  )
  "certificateExpWarning" 10
  "variables" (dict
    "dateFormat" "DD/MM/YYYY"
    "dateTimeFormat" "DD/MM/YYYY HH:mm"
  )
  "defaultRoute" "/messages"
  "backendUrl" (printf "%s://%s" (include "liquio.scheme" .) (include "liquio.publicHost" (dict "ctx" . "service" "cabinet-api")))
  "authLink" (printf "%s://%s/redirect/auth" (include "liquio.scheme" .) (include "liquio.publicHost" (dict "ctx" . "service" "cabinet-api")))
  "idAuthLink" (printf "%s://%s/authorise" (include "liquio.scheme" .) (include "liquio.publicHost" (dict "ctx" . "service" "id")))
  "clientId" "liquio-portal"
  "defaultLanguage" "en-GB"
}}
data:
  config.json: |
{{ include "liquio.renderJsonConfig" (dict "ctx" . "service" "cabinetFront" "config" "config" "base" $configBase) | nindent 4 }}
