{{- if not .Values.secrets.existingSecretConfig }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.secretConfig.name" (dict "ctx" . "service" "cabinet-api") }}
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
    app.kubernetes.io/component: cabinet-api
type: Opaque
stringData:
  db.json: |
    { "password": "{{ include "liquio.postgresql.passwordValue" . }}" }
  auth.json: |
    { "LiquioId": { "clientSecret": "{{ include "liquio.oauth.secretKeyValue" . }}", "basicAuthToken": "{{ include "liquio.oauth.secretKeyValue" . }}" }, "jwtSecret": "{{ include "liquio.jwt.secretValue" . }}" }
{{- end }}
