{{- if not .Values.secrets.existingSecretConfig }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.secretConfig.name" (dict "ctx" . "service" "id") }}
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
    app.kubernetes.io/component: id-api
type: Opaque
stringData:
  config.json: |
    {
      "production": {
        "db": { "password": "{{ include "liquio.postgresql.passwordValue" . }}" },
        "session": { "secret_key": "{{ include "liquio.oauth.secretKeyValue" . }}" },
        "jwt": { "secret": "{{ include "liquio.jwt.secretValue" . }}" },
        "oauth": { "secret_key": ["{{ include "liquio.oauth.secretKeyValue" . }}"] },
        "notify": { "authorization": "Basic {{ include "liquio.notification.userValue" . }}:{{ include "liquio.notification.passwordValue" . }}" }
      }
    }
{{- end }}
