{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.secrets.name" . }}
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ include "liquio.postgresql.passwordValue" . | b64enc | quote }}
  rabbitmq-password: {{ include "liquio.rabbitmq.passwordValue" . | b64enc | quote }}
  oauth-secret-key: {{ include "liquio.oauth.secretKeyValue" . | b64enc | quote }}
  jwt-secret: {{ include "liquio.jwt.secretValue" . | b64enc | quote }}
  register-encryption-key: {{ include "liquio.register.encryptionKeyValue" . | b64enc | quote }}
  register-auth-token: {{ include "liquio.register.authTokenValue" . | b64enc | quote }}
  external-reader-auth-token: {{ include "liquio.externalReader.authTokenValue" . | b64enc | quote }}
  filestorage-auth-token: {{ include "liquio.filestorage.authTokenValue" . | b64enc | quote }}
{{- end }}
