import sanitizeHtml from 'sanitize-html';

const sanitizeOptions = {
  allowedTags: [
    'a',
    'p',
    'span',
    'div',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'ul',
    'ol',
    'li',
    'b',
    'i',
    'u',
    's',
    'em',
    'strong',
    'strike',
    'sub',
    'sup',
    'hr',
    'br',
    'blockquote',
    'caption',
    'code',
    'pre',
    'col',
    'colgroup',
    'table',
    'tbody',
    'td',
    'tfoot',
    'th',
    'thead',
    'tr',
    'section',
    'footer',
  ],
  allowedAttributes: {
    a: ['href', 'name', 'target', 'rel', 'class', 'style'],
    span: ['class', 'style'],
    p: ['class', 'style'],
    li: ['class', 'style'],
    pre: ['class', 'style'],
    footer: ['class', 'style'],
    section: ['class', 'style'],
    div: ['class', 'style'],
  },
  allowedClasses: {
    '*': [
      'ql-align-right',
      'ql-align-center',
      'ql-align-justify',
      'ql-code-block',
      'ql-code-block-container',
      'ql-syntax',
      'ql-direction-rtl',
      'ql-font-serif',
      'ql-font-monospace',
      'ql-formula',
      'ql-indent-1',
      'ql-indent-2',
      'ql-indent-3',
      'ql-indent-4',
      'ql-indent-5',
      'ql-indent-6',
      'ql-indent-7',
      'ql-indent-8',
      'ql-indent-2em',
      'ql-size-small',
      'ql-size-large',
      'ql-size-huge',
      'first-line-indent-3em',
    ],
  },
  parseStyleAttributes: false,
};

export default (html) => sanitizeHtml(html, sanitizeOptions);
